; Error return codes for handles.
ERROR_HANDLE_FILE_OPEN			=	-1
ERROR_HANDLE_HEADER_NOT_FOUND	=	-2
ERROR_HANDLE_ALLOCATE_FAIL		=	-3
ERROR_HANDLE_FILE_READ			=	-4
ERROR_HANDLE_RNC				=	-5
ERROR_HANDLE_GENERIC			=	-6
ERROR_HANDLE_UNPACK				=	-7